#message:2F:(Club64_ElderScene_0)
{
[Style right]
Well... That took longer than I[BR]
wanted it to...[BR]
[Wait][Next]
At least I am not the last[BR]
one...[Pause 15] [Speed delay=2 chars=1]here...[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_1)
{
[Style right]
[Shake]Ah! Goompa, you finally made it![BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_2)
{
[Style right]
[Pause 20][Speed delay=3 chars=1]Sigh... [Speed delay=1 chars=1]Just how late am I?[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_3)
{
[Style right]
[Shake]Just 2 hours.[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_4)
{
[Style right]
[PrintRising]What do you mean just[BR]
2 hours!?![BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_5)
{
[Style right]
Be calm. I am glad you made it[BR]
here.[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_6)
{
[Style right]
I am sorry, I just don't like[BR]
being late.[BR]
[Wait][Next]
How did you guys get here before[BR]
me anyways?[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_7)
{
[Style right]
[Shake][Color 0x23]Blue Pipe[Color 0xA].[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_8)
{
[Style right]
[Color 0x23]Blue Pipe[Color 0xA].[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_9)
{
[Style right]
[Color 0x23]Blue Pipe[Color 0xA].[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_10)
{
[Style right]
[Color 0x25]Green Pipe[Color 0xA].[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_11)
{
[Style right]
Is your [Color 0x23]Blue Pipe [Color 0xA]not working?[BR]
[Wait][Next]
I thought I asked for it to be[BR]
properly installed for[BR]
Goomba Village at this[BR]
point in time.[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_12)
{
[Style right]
Wait, so why is there a[BR]
[Color 0x23]Blue Pipe[Color 0xA]?[BR]
[Wait][Next]
I have seen Goombaria[BR]
use it often lately.[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_13)
{
[Style right]
The Princess wanted her[BR]
people to have a shortcut to[BR]
Toad Town.[BR]
[Wait][Next]
She does not want people to[BR]
have to travel so long and[BR]
hard on foot.[BR]
[Wait][Next]
She knows how dangerous it can[BR]
be to travel in the kingdom with[BR]
there not being enough resting[BR]
spots.[BR]
[Wait][Next]
But it sounds like your [Color 0x23]Blue Pipe[BR]
[Color 0xA]is working. I was worried there[BR]
for a moment.[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_14)
{
[Style right]
[PrintRising]Why was there no communication[BR]
with me about this!?![BR]
[Wait][Next]
If I had known about it, I would[BR]
not have gotten here so late![BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_15)
{
[Style right]
I-[Pause 5][BR]
[End]
}








#message:2F:(Club64_ElderScene_16)
{
[Style right]
[PrintRising][Size 32,32][CenterX 160][Down 10]Enough![BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_17)
{
[Style right]
Stop this bickering. All that[BR]
matters is that you came here.[BR]
Isn't that right, Master?[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_18)
{
[Style right]
Indeed. I am just glad you all[BR]
came here at my request.[BR]
[Wait][Next]
[Speed delay=4 chars=1][Pause 10]Now [Pause 5]then...[BR]
[Wait][Next]
[Speed delay=2 chars=1]It is time to talk about how to[BR]
guide the future generation.[BR]
[Wait][Next]
As leaders and elders, do you[BR]
have plans for your community[BR]
and loved ones' lives?[BR]
[Wait][Next]
If you all could give me a[BR]
answer please. [Speed delay=1 chars=1][Pause 15]The future[BR]
will always be sooner than[BR]
we expect.[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_19)
{
[Style right]
Wait, why are we talking about[BR]
the future generation?[BR]
[Wait][Next]
We always come to you if we have[BR]
trouble guiding our communities[BR]
and loved ones.[BR]
[Wait][Next]
We can't really plan for[BR]
everything. Life is unpredictable.[BR]
[Wait][Next]
[Pause 12]Wait[Pause 4].[Pause 4].[Pause 4].[BR]
[Wait][Next]
All of us are gathered[BR]
here today.[BR]
[Wait][Next]
Why did you request all of us[BR]
to come here?[BR]
[Wait][Next]
What's wrong?[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_20)
{
[Style right]
[PrintRising][Shake]...cough hack cough...[BR]
[Wait][Next]
Don't worry about me![BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_21)
{
[Style right]
You should tell them.[BR]
[Wait][Next]
They won't answer you until[BR]
you do.[BR]
[Wait][End]
}








#message:2F:(Club64_ElderScene_22)
{
[Style right]
Of course, you are aware.[BR]
[Wait][Next]
[Speed delay=3 chars=1][Pause 12]Very well then[Pause 4].[Pause 4].[Pause 4].[BR]
[Wait][Next]
[Speed delay=2 chars=1]My time here is getting closer[BR]
to ending any moment now.[BR]
[Wait][Next]
Just so you all know.[BR]
[Wait][Next]
Nobody else knows about this[BR]
except all of you now.[BR]
[Wait][Next]
My students have started a[BR]
rumor about this.[BR]
[Wait][Next]
But they don't know it is true.[BR]
[Wait][Next]
I believe it has been[BR]
spreading outside the town.[BR]
[Wait][End]
}







#message:2F:(Club64_ElderScene_23)
{
[Style right]
[Speed delay=2 chars=1]What is this?[BR]
[Wait][Next]
[Speed delay=3 chars=1]I feel weird all of a sudden...[BR]
[Wait][Next]
[PrintRising][Speed delay=1 chars=2]My body![BR]
[Wait][Next]
[Speed delay=5 chars=1][Shake]We should go outside,[BR]
perhaps I need fresh air...[BR]
[Wait][End]
}





#message:2F:(StarSanctuary_LakumiScene_0)
{
[Style right]
Why does everyone act like[BR]
I’m nothing?[BR]
[Wait][Next]
[Pause 30]I’m trying.[BR]
[Wait][Next]
I just want people to stop[BR]
treating me like trash.[BR]
[Wait][Next]
[PrintRising][Pause 15]That’s it.[/fx][BR]
[Wait][Next]
I’m so tired of pretending[BR]
I’m okay.[BR]
[Wait][Next]
If I had a little power, maybe[BR]
they’d stop picking on me.[BR]
[Wait][End]
}

